#ifndef MAKESOUNDONBUILD_GLOBAL_H
#define MAKESOUNDONBUILD_GLOBAL_H

#include <QtGlobal>

#if defined(MAKESOUNDONBUILD_LIBRARY)
#  define MAKESOUNDONBUILDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MAKESOUNDONBUILDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MAKESOUNDONBUILD_GLOBAL_H

